import pickle
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import streamlit as st


MODEL_PATH = Path("model/predictive_maintenance_model.pkl")

FEATURE_LABELS = {
    "Air temperature [K]": "Air Temperature (K)",
    "Process temperature [K]": "Process Temperature (K)",
    "Rotational speed [rpm]": "Rotational Speed (RPM)",
    "Torque [Nm]": "Torque (Nm)",
    "Tool wear [min]": "Tool Wear (minutes)",
}

FEATURE_DESCRIPTIONS = {
    "Air Temperature": "Temperature of the surrounding air near the machine.",
    "Process Temperature": "Operating temperature generated by the manufacturing process.",
    "Rotational Speed": "Speed of the rotating component, measured in revolutions per minute.",
    "Torque": "Rotational force applied by the machine during operation.",
    "Tool Wear": "Total time the tool has been used, measured in minutes.",
}


def load_model_package():
    if not MODEL_PATH.exists():
        return None

    with open(MODEL_PATH, "rb") as file:
        return pickle.load(file)


def get_risk_level(failure_probability: float) -> str:
    if failure_probability >= 0.70:
        return "High"
    if failure_probability >= 0.35:
        return "Medium"
    return "Low"


def validate_inputs(values: dict) -> list[str]:
    errors = []

    if not 250 <= values["Air temperature [K]"] <= 350:
        errors.append("Air Temperature should be between 250 K and 350 K.")
    if not 250 <= values["Process temperature [K]"] <= 400:
        errors.append("Process Temperature should be between 250 K and 400 K.")
    if not 500 <= values["Rotational speed [rpm]"] <= 4000:
        errors.append("Rotational Speed should be between 500 RPM and 4000 RPM.")
    if not 1 <= values["Torque [Nm]"] <= 100:
        errors.append("Torque should be between 1 Nm and 100 Nm.")
    if not 0 <= values["Tool wear [min]"] <= 300:
        errors.append("Tool Wear should be between 0 and 300 minutes.")

    return errors


def render_feature_importance_chart(feature_importance: pd.DataFrame) -> None:
    chart_data = feature_importance.sort_values("importance", ascending=True)
    labels = [FEATURE_LABELS.get(feature, feature) for feature in chart_data["feature"]]

    fig, ax = plt.subplots(figsize=(8, 4.8))
    colors = ["#1f77b4", "#2ca02c", "#ff7f0e", "#d62728", "#9467bd"]
    ax.barh(labels, chart_data["importance"], color=colors[: len(labels)])
    ax.set_xlabel("Importance Score")
    ax.set_title("Random Forest Feature Importance")
    ax.grid(axis="x", alpha=0.2)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    st.pyplot(fig, use_container_width=True)


def render_probability_chart(failure_probability: float) -> None:
    safe_probability = 1 - failure_probability
    labels = ["No Failure", "Failure"]
    values = [safe_probability, failure_probability]
    colors = ["#2ca02c", "#d62728"]

    fig, ax = plt.subplots(figsize=(6.5, 3.8))
    ax.bar(labels, values, color=colors)
    ax.set_ylim(0, 1)
    ax.set_ylabel("Probability")
    ax.set_title("Prediction Probability")
    ax.grid(axis="y", alpha=0.2)

    for index, value in enumerate(values):
        ax.text(index, value + 0.03, f"{value * 100:.1f}%", ha="center", fontweight="bold")

    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    st.pyplot(fig, use_container_width=True)


st.set_page_config(
    page_title="Predictive Maintenance AI",
    page_icon="",
    layout="wide",
)

st.markdown(
    """
    <style>
        .stApp {
            background: linear-gradient(135deg, #f8fbff 0%, #eef4f8 45%, #f7f7fb 100%);
        }
        .main-header {
            padding: 1.5rem 0 0.75rem;
        }
        .main-header h1 {
            color: #102033;
            font-size: 2.6rem;
            margin-bottom: 0.4rem;
        }
        .main-header p {
            color: #516070;
            font-size: 1.05rem;
            max-width: 760px;
        }
        h2, h3, label, .stMarkdown, [data-testid="stMarkdownContainer"] {
            color: #102033 !important;
        }
        [data-testid="stMetricLabel"], [data-testid="stMetricValue"] {
            color: #102033 !important;
        }
        [data-testid="stMetricDelta"] {
            color: #516070 !important;
        }
        .stNumberInput label p {
            color: #102033 !important;
            font-weight: 650;
        }
        .metric-card {
            background: white;
            border: 1px solid #dce5ec;
            border-radius: 8px;
            padding: 1.1rem;
            box-shadow: 0 8px 24px rgba(16, 32, 51, 0.06);
            min-height: 120px;
        }
        .metric-label {
            color: #637083;
            font-size: 0.86rem;
            margin-bottom: 0.3rem;
        }
        .metric-value {
            color: #102033;
            font-size: 1.75rem;
            font-weight: 750;
        }
        .risk-low {
            border-left: 7px solid #2ca02c;
        }
        .risk-medium {
            border-left: 7px solid #ffb000;
        }
        .risk-high {
            border-left: 7px solid #d62728;
        }
        .info-box {
            background: white;
            border: 1px solid #dce5ec;
            border-radius: 8px;
            padding: 1rem 1.1rem;
            margin-bottom: 0.8rem;
        }
        .info-box strong {
            color: #102033;
        }
        .info-box span {
            color: #596779;
        }
        div.stButton > button {
            width: 100%;
            border-radius: 8px;
            background: #1264a3;
            color: white;
            border: 0;
            padding: 0.75rem 1rem;
            font-weight: 700;
        }
        div.stButton > button:hover {
            background: #0f5488;
            color: white;
        }
    </style>
    """,
    unsafe_allow_html=True,
)

st.markdown(
    """
    <div class="main-header">
        <h1>Predictive Maintenance AI Dashboard</h1>
        <p>
            Enter machine operating parameters to estimate failure risk in real time.
            The prediction is powered by a Random Forest model trained on the AI4I 2020
            Predictive Maintenance Dataset.
        </p>
    </div>
    """,
    unsafe_allow_html=True,
)

model_package = load_model_package()

if model_package is None:
    st.error("Trained model not found. Run `python train_model.py` first, then start Streamlit again.")
    st.stop()

model = model_package["model"]
features = model_package["features"]
feature_importance = model_package["feature_importance"]

left_column, right_column = st.columns([1, 1.15], gap="large")

with left_column:
    st.subheader("Machine Input Form")

    with st.form("prediction_form"):
        air_temperature = st.number_input(
            "Air Temperature (K)",
            min_value=250.0,
            max_value=350.0,
            value=300.0,
            step=0.1,
        )
        process_temperature = st.number_input(
            "Process Temperature (K)",
            min_value=250.0,
            max_value=400.0,
            value=310.0,
            step=0.1,
        )
        rotational_speed = st.number_input(
            "Rotational Speed (RPM)",
            min_value=500,
            max_value=4000,
            value=1500,
            step=10,
        )
        torque = st.number_input(
            "Torque (Nm)",
            min_value=1.0,
            max_value=100.0,
            value=40.0,
            step=0.1,
        )
        tool_wear = st.number_input(
            "Tool Wear (minutes)",
            min_value=0,
            max_value=300,
            value=120,
            step=1,
        )

        submitted = st.form_submit_button("Predict Machine Failure Risk")

    input_values = {
        "Air temperature [K]": air_temperature,
        "Process temperature [K]": process_temperature,
        "Rotational speed [rpm]": rotational_speed,
        "Torque [Nm]": torque,
        "Tool wear [min]": tool_wear,
    }

    st.subheader("Feature Descriptions")
    for name, description in FEATURE_DESCRIPTIONS.items():
        st.markdown(
            f"""
            <div class="info-box">
                <strong>{name}</strong><br>
                <span>{description}</span>
            </div>
            """,
            unsafe_allow_html=True,
        )

with right_column:
    st.subheader("Prediction Dashboard")

    input_errors = validate_inputs(input_values)

    if submitted and input_errors:
        for error in input_errors:
            st.warning(error)

    if submitted and not input_errors:
        input_df = pd.DataFrame([input_values], columns=features)
        prediction = int(model.predict(input_df)[0])
        prediction_probabilities = model.predict_proba(input_df)[0]
        failure_probability = float(prediction_probabilities[1])
        confidence = float(np.max(prediction_probabilities))
        risk_level = get_risk_level(failure_probability)

        risk_class = {
            "Low": "risk-low",
            "Medium": "risk-medium",
            "High": "risk-high",
        }[risk_level]

        result_text = "Yes" if prediction == 1 else "No"

        card_one, card_two, card_three = st.columns(3)
        with card_one:
            st.markdown(
                f"""
                <div class="metric-card {risk_class}">
                    <div class="metric-label">Machine Failure Risk</div>
                    <div class="metric-value">{result_text}</div>
                </div>
                """,
                unsafe_allow_html=True,
            )
        with card_two:
            st.markdown(
                f"""
                <div class="metric-card">
                    <div class="metric-label">Prediction Confidence</div>
                    <div class="metric-value">{confidence * 100:.1f}%</div>
                </div>
                """,
                unsafe_allow_html=True,
            )
        with card_three:
            st.markdown(
                f"""
                <div class="metric-card {risk_class}">
                    <div class="metric-label">Risk Level</div>
                    <div class="metric-value">{risk_level}</div>
                </div>
                """,
                unsafe_allow_html=True,
            )

        st.progress(failure_probability, text=f"Failure probability: {failure_probability * 100:.1f}%")
        render_probability_chart(failure_probability)

    else:
        st.info("Enter machine values and click the prediction button to see the dashboard.")

    st.subheader("Model Insights")
    metric_one, metric_two = st.columns(2)
    metric_one.metric("Test Accuracy", f"{model_package['accuracy'] * 100:.2f}%")
    metric_two.metric("ROC AUC", f"{model_package['roc_auc']:.3f}")
    render_feature_importance_chart(feature_importance)
