import pickle
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import streamlit as st


MODEL_PATH = Path("model/predictive_maintenance_model.pkl")

FEATURE_LABELS = {
    "Air temperature [K]": "Air Temperature (K)",
    "Process temperature [K]": "Process Temperature (K)",
    "Rotational speed [rpm]": "Rotational Speed (RPM)",
    "Torque [Nm]": "Torque (Nm)",
    "Tool wear [min]": "Tool Wear (minutes)",
}

FEATURE_DESCRIPTIONS = {
    "Air Temperature": "Temperature of the surrounding air near the machine.",
    "Process Temperature": "Operating temperature generated by the manufacturing process.",
    "Rotational Speed": "Speed of the rotating component, measured in revolutions per minute.",
    "Torque": "Rotational force applied by the machine during operation.",
    "Tool Wear": "Total time the tool has been used, measured in minutes.",
}


def load_model_package():
    if not MODEL_PATH.exists():
        return None

    with open(MODEL_PATH, "rb") as file:
        return pickle.load(file)


def get_risk_level(failure_probability: float) -> str:
    if failure_probability >= 0.70:
        return "High"
    if failure_probability >= 0.35:
        return "Medium"
    return "Low"


def validate_inputs(values: dict) -> list[str]:
    errors = []

    if not 250 <= values["Air temperature [K]"] <= 350:
        errors.append("Air Temperature should be between 250 K and 350 K.")
    if not 250 <= values["Process temperature [K]"] <= 400:
        errors.append("Process Temperature should be between 250 K and 400 K.")
    if not 500 <= values["Rotational speed [rpm]"] <= 4000:
        errors.append("Rotational Speed should be between 500 RPM and 4000 RPM.")
    if not 1 <= values["Torque [Nm]"] <= 100:
        errors.append("Torque should be between 1 Nm and 100 Nm.")
    if not 0 <= values["Tool wear [min]"] <= 300:
        errors.append("Tool Wear should be between 0 and 300 minutes.")

    return errors


def render_feature_importance_chart(feature_importance: pd.DataFrame) -> None:
    chart_data = feature_importance.sort_values("importance", ascending=True)
    labels = [FEATURE_LABELS.get(feature, feature) for feature in chart_data["feature"]]

    fig, ax = plt.subplots(figsize=(8, 4.8))
    fig.patch.set_facecolor("#111827")
    ax.set_facecolor("#111827")
    colors = ["#38bdf8", "#22c55e", "#f59e0b", "#ef4444", "#a78bfa"]
    ax.barh(labels, chart_data["importance"], color=colors[: len(labels)])
    ax.set_xlabel("Importance Score", color="#cbd5e1")
    ax.set_title("Random Forest Feature Importance", color="#f8fafc", pad=14)
    ax.tick_params(colors="#cbd5e1")
    ax.grid(axis="x", color="#334155", alpha=0.55)
    ax.spines["left"].set_color("#475569")
    ax.spines["bottom"].set_color("#475569")
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    st.pyplot(fig, use_container_width=True)


def render_probability_chart(failure_probability: float) -> None:
    safe_probability = 1 - failure_probability
    labels = ["No Failure", "Failure"]
    values = [safe_probability, failure_probability]
    colors = ["#22c55e", "#ef4444"]

    fig, ax = plt.subplots(figsize=(6.5, 3.8))
    fig.patch.set_facecolor("#111827")
    ax.set_facecolor("#111827")
    ax.bar(labels, values, color=colors)
    ax.set_ylim(0, 1)
    ax.set_ylabel("Probability", color="#cbd5e1")
    ax.set_title("Prediction Probability", color="#f8fafc", pad=14)
    ax.tick_params(colors="#cbd5e1")
    ax.grid(axis="y", color="#334155", alpha=0.55)

    for index, value in enumerate(values):
        ax.text(
            index,
            value + 0.03,
            f"{value * 100:.1f}%",
            ha="center",
            fontweight="bold",
            color="#f8fafc",
        )

    ax.spines["left"].set_color("#475569")
    ax.spines["bottom"].set_color("#475569")
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    st.pyplot(fig, use_container_width=True)


st.set_page_config(
    page_title="Predictive Maintenance AI",
    page_icon="",
    layout="wide",
)

st.markdown(
    """
    <style>
        .stApp {
            background:
                radial-gradient(circle at 18% 10%, rgba(56, 189, 248, 0.18), transparent 28%),
                radial-gradient(circle at 85% 8%, rgba(34, 197, 94, 0.12), transparent 24%),
                linear-gradient(135deg, #020617 0%, #0f172a 48%, #030712 100%);
            color: #f8fafc;
        }
        [data-testid="stHeader"] {
            background: rgba(2, 6, 23, 0);
        }
        [data-testid="stToolbar"] {
            right: 1rem;
        }
        .block-container {
            padding-top: 2.2rem;
            padding-bottom: 3rem;
        }
        .main-header {
            background: linear-gradient(135deg, rgba(15, 23, 42, 0.94), rgba(17, 24, 39, 0.88));
            border: 1px solid rgba(148, 163, 184, 0.22);
            border-radius: 8px;
            padding: 1.6rem 1.7rem;
            margin-bottom: 1.5rem;
            box-shadow: 0 22px 60px rgba(0, 0, 0, 0.34);
        }
        .main-header h1 {
            color: #f8fafc;
            font-size: 2.65rem;
            margin-bottom: 0.4rem;
            letter-spacing: 0;
        }
        .main-header p {
            color: #cbd5e1;
            font-size: 1.05rem;
            max-width: 760px;
        }
        .hero-badges {
            display: flex;
            flex-wrap: wrap;
            gap: 0.55rem;
            margin-top: 1rem;
        }
        .hero-badge {
            background: rgba(14, 165, 233, 0.14);
            border: 1px solid rgba(56, 189, 248, 0.32);
            border-radius: 999px;
            color: #bae6fd;
            font-size: 0.82rem;
            font-weight: 700;
            padding: 0.35rem 0.7rem;
        }
        h2, h3, label, .stMarkdown, [data-testid="stMarkdownContainer"] {
            color: #f8fafc !important;
        }
        [data-testid="stMetricLabel"], [data-testid="stMetricValue"] {
            color: #f8fafc !important;
        }
        [data-testid="stMetricDelta"] {
            color: #cbd5e1 !important;
        }
        .stNumberInput label p {
            color: #e2e8f0 !important;
            font-weight: 650;
        }
        [data-testid="stForm"] {
            background: rgba(15, 23, 42, 0.78);
            border: 1px solid rgba(148, 163, 184, 0.22);
            border-radius: 8px;
            padding: 1.1rem 1.15rem 1.25rem;
            box-shadow: 0 18px 45px rgba(0, 0, 0, 0.25);
        }
        [data-testid="stNumberInput"] input {
            background: #020617 !important;
            border: 1px solid #334155 !important;
            color: #f8fafc !important;
            border-radius: 8px !important;
        }
        [data-testid="stNumberInput"] button {
            background: #111827 !important;
            color: #e2e8f0 !important;
            border-color: #334155 !important;
        }
        .metric-card {
            background: linear-gradient(180deg, rgba(17, 24, 39, 0.98), rgba(15, 23, 42, 0.98));
            border: 1px solid rgba(148, 163, 184, 0.24);
            border-radius: 8px;
            padding: 1.1rem;
            box-shadow: 0 16px 40px rgba(0, 0, 0, 0.28);
            min-height: 120px;
        }
        .metric-label {
            color: #94a3b8;
            font-size: 0.86rem;
            margin-bottom: 0.3rem;
        }
        .metric-value {
            color: #f8fafc;
            font-size: 1.55rem;
            font-weight: 750;
            line-height: 1.12;
            white-space: nowrap;
        }
        .risk-low {
            border-left: 7px solid #22c55e;
        }
        .risk-medium {
            border-left: 7px solid #f59e0b;
        }
        .risk-high {
            border-left: 7px solid #ef4444;
        }
        .info-box {
            background: rgba(15, 23, 42, 0.82);
            border: 1px solid rgba(148, 163, 184, 0.22);
            border-radius: 8px;
            padding: 1rem 1.1rem;
            margin-bottom: 0.8rem;
            box-shadow: 0 12px 30px rgba(0, 0, 0, 0.18);
        }
        .info-box strong {
            color: #f8fafc;
        }
        .info-box span {
            color: #cbd5e1;
        }
        [data-testid="stAlert"] {
            background: rgba(14, 165, 233, 0.12);
            border: 1px solid rgba(56, 189, 248, 0.32);
            border-radius: 8px;
            color: #e0f2fe;
        }
        [data-testid="stProgress"] > div > div > div {
            background-color: #38bdf8;
        }
        div.stButton > button,
        div.stFormSubmitButton > button {
            width: 100%;
            border-radius: 8px;
            background: linear-gradient(135deg, #0284c7, #16a34a);
            color: white;
            border: 0;
            padding: 0.75rem 1rem;
            font-weight: 700;
            box-shadow: 0 16px 35px rgba(2, 132, 199, 0.28);
        }
        div.stButton > button:hover,
        div.stFormSubmitButton > button:hover {
            background: linear-gradient(135deg, #0369a1, #15803d);
            color: white;
        }
    </style>
    """,
    unsafe_allow_html=True,
)

st.markdown(
    """
    <div class="main-header">
        <h1>Predictive Maintenance AI Dashboard</h1>
        <p>
            Enter machine operating parameters to estimate failure risk in real time.
            The prediction is powered by a Random Forest model trained on the AI4I 2020
            Predictive Maintenance Dataset.
        </p>
        <div class="hero-badges">
            <span class="hero-badge">Random Forest</span>
            <span class="hero-badge">Real-time Risk Score</span>
            <span class="hero-badge">AI4I 2020 Dataset</span>
        </div>
    </div>
    """,
    unsafe_allow_html=True,
)

model_package = load_model_package()

if model_package is None:
    st.error("Trained model not found. Run `python train_model.py` first, then start Streamlit again.")
    st.stop()

model = model_package["model"]
features = model_package["features"]
feature_importance = model_package["feature_importance"]

left_column, right_column = st.columns([1, 1.15], gap="large")

with left_column:
    st.subheader("Machine Input Form")

    with st.form("prediction_form"):
        air_temperature = st.number_input(
            "Air Temperature (K)",
            min_value=250.0,
            max_value=350.0,
            value=300.0,
            step=0.1,
        )
        process_temperature = st.number_input(
            "Process Temperature (K)",
            min_value=250.0,
            max_value=400.0,
            value=310.0,
            step=0.1,
        )
        rotational_speed = st.number_input(
            "Rotational Speed (RPM)",
            min_value=500,
            max_value=4000,
            value=1500,
            step=10,
        )
        torque = st.number_input(
            "Torque (Nm)",
            min_value=1.0,
            max_value=100.0,
            value=40.0,
            step=0.1,
        )
        tool_wear = st.number_input(
            "Tool Wear (minutes)",
            min_value=0,
            max_value=300,
            value=120,
            step=1,
        )

        submitted = st.form_submit_button("Predict Machine Failure Risk")

    input_values = {
        "Air temperature [K]": air_temperature,
        "Process temperature [K]": process_temperature,
        "Rotational speed [rpm]": rotational_speed,
        "Torque [Nm]": torque,
        "Tool wear [min]": tool_wear,
    }

    st.subheader("Feature Descriptions")
    for name, description in FEATURE_DESCRIPTIONS.items():
        st.markdown(
            f"""
            <div class="info-box">
                <strong>{name}</strong><br>
                <span>{description}</span>
            </div>
            """,
            unsafe_allow_html=True,
        )

with right_column:
    st.subheader("Prediction Dashboard")

    input_errors = validate_inputs(input_values)

    if submitted and input_errors:
        for error in input_errors:
            st.warning(error)

    if submitted and not input_errors:
        input_df = pd.DataFrame([input_values], columns=features)
        prediction = int(model.predict(input_df)[0])
        prediction_probabilities = model.predict_proba(input_df)[0]
        failure_probability = float(prediction_probabilities[1])
        confidence = float(np.max(prediction_probabilities))
        risk_level = get_risk_level(failure_probability)

        risk_class = {
            "Low": "risk-low",
            "Medium": "risk-medium",
            "High": "risk-high",
        }[risk_level]

        result_text = "Yes" if prediction == 1 else "No"

        card_one, card_two, card_three = st.columns(3)
        with card_one:
            st.markdown(
                f"""
                <div class="metric-card {risk_class}">
                    <div class="metric-label">Machine Failure Risk</div>
                    <div class="metric-value">{result_text}</div>
                </div>
                """,
                unsafe_allow_html=True,
            )
        with card_two:
            st.markdown(
                f"""
                <div class="metric-card">
                    <div class="metric-label">Prediction Confidence</div>
                    <div class="metric-value">{confidence * 100:.1f}%</div>
                </div>
                """,
                unsafe_allow_html=True,
            )
        with card_three:
            st.markdown(
                f"""
                <div class="metric-card {risk_class}">
                    <div class="metric-label">Risk Level</div>
                    <div class="metric-value">{risk_level}</div>
                </div>
                """,
                unsafe_allow_html=True,
            )

        st.progress(failure_probability, text=f"Failure probability: {failure_probability * 100:.1f}%")
        render_probability_chart(failure_probability)

    else:
        st.info("Enter machine values and click the prediction button to see the dashboard.")

    st.subheader("Model Insights")
    metric_one, metric_two = st.columns(2)
    metric_one.metric("Test Accuracy", f"{model_package['accuracy'] * 100:.2f}%")
    metric_two.metric("ROC AUC", f"{model_package['roc_auc']:.3f}")
    render_feature_importance_chart(feature_importance)
